global:
  pattern: rag-llm-cpu
  embeddingModel: sentence-transformers/all-mpnet-base-v2
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/dminnear-rh/clustergroup-chart
    clusterGroupChartGitRevision: pattern-delete
